'use client'

import { nanoid } from 'nanoid'
import GlobalDropdown from '@/components/ui/GlobalDropdown'
import { calculateFinancialModel, createPaymentPlan, createPaymentStage, formatFinancialAmount, normalizePaymentPlan, type AdditionalCost, type Financing, type PaymentPlan, type PaymentStage, type RecurringCost } from '@/lib/paymentPlan'

export default function PaymentPlanBuilder({ value, price, currency, areaSquareFeet, onChange }: { value: unknown; price?: number | null; currency?: string | null; areaSquareFeet?: number | null; onChange: (plan: PaymentPlan) => void }) {
  const plan = normalizePaymentPlan(value)
  const calculation = calculateFinancialModel(plan, price, areaSquareFeet)
  const money = (amount: number) => formatFinancialAmount(amount, currency || '')
  const update = (patch: Partial<PaymentPlan>) => onChange(createPaymentPlan({ ...plan, ...patch }))
  const updateStage = (index: number, patch: Partial<PaymentStage>) => update({ stages: plan.stages.map((stage, current) => current === index ? { ...stage, ...patch } : stage) })
  const add = () => update({ stages: [...plan.stages, createPaymentStage({ id: nanoid(8), type: 'CUSTOM', label: 'Payment stage', order: plan.stages.length })] })
  const remove = (index: number) => update({ stages: plan.stages.filter((_, current) => current !== index).map((stage, order) => ({ ...stage, order })) })
  const addCost = () => update({ additionalCosts: [...plan.additionalCosts, { id: nanoid(8), category: 'OTHER_ONE_TIME_FEE', label: '', basis: 'FIXED_AMOUNT', amount: 0, payer: 'BUYER', timing: 'CONTRACT', recurring: false }] as AdditionalCost[] })
  const updateCost = (index: number, patch: Partial<AdditionalCost>) => update({ additionalCosts: plan.additionalCosts.map((cost, current) => current === index ? { ...cost, ...patch } : cost) })
  const addRecurring = () => update({ recurringCosts: [...plan.recurringCosts, { id: nanoid(8), category: 'SERVICE_CHARGE', label: '', basis: 'FIXED_AMOUNT', amount: 0, frequency: 'ANNUALLY', status: 'ESTIMATED' }] as RecurringCost[] })
  const updateRecurring = (index: number, patch: Partial<RecurringCost>) => update({ recurringCosts: plan.recurringCosts.map((cost, current) => current === index ? { ...cost, ...patch } : cost) })
  const financing = plan.financing || { available: 'NOT_SPECIFIED', source: 'NOT_SPECIFIED' } as Financing
  const updateFinancing = (patch: Partial<Financing>) => update({ financing: { ...financing, ...patch } })
  const inputClass = 'mt-1 h-10 w-full rounded-lg border border-gray-300 px-2 text-sm text-dark-blue'
  const timingOptions = [['AT_BOOKING', 'At booking'], ['AFTER_DAYS', 'After X days'], ['AFTER_MONTHS', 'After X months'], ['MONTHLY', 'Monthly'], ['QUARTERLY', 'Quarterly'], ['AT_CONSTRUCTION_MILESTONE', 'At construction milestone'], ['AT_HANDOVER', 'At handover'], ['AFTER_HANDOVER', 'After handover'], ['CUSTOM_DATE', 'Custom date']] as const
  const typeOptions = [['BOOKING', 'Booking'], ['INITIAL_PAYMENT', 'Initial payment'], ['MONTHLY_INSTALLMENT', 'Monthly instalment'], ['QUARTERLY_INSTALLMENT', 'Quarterly instalment'], ['CONSTRUCTION_MILESTONE', 'Construction milestone'], ['CUSTOM_MILESTONE', 'Custom milestone'], ['HANDOVER', 'Handover'], ['POST_HANDOVER', 'Post-handover'], ['FINAL_PAYMENT', 'Final payment'], ['CUSTOM', 'Custom']] as const

  const dropdown = (value: string, options: readonly (readonly [string, string])[], onChange: (value: string) => void, label: string) => <GlobalDropdown label={label} value={value} onChange={(next) => onChange(String(next))} options={options.map(([optionValue, optionLabel]) => ({ value: optionValue, label: optionLabel }))} appearance="admin-light" dense />

  return <div className="md:col-span-2 rounded-2xl border border-gray-200 bg-gray-50 p-5 space-y-6">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold text-dark-blue">Payment plan</p><p className="mt-1 text-xs text-gray-600">Define how the property price is paid. Costs and financing stay separate.</p></div><p className="text-lg font-bold text-dark-blue">{money(calculation.propertyPrice)}</p></div>
    <div className="flex flex-wrap gap-4 text-sm text-gray-700">{(['PERCENTAGE', 'FIXED', 'MIXED'] as const).map((mode) => <label key={mode} className="inline-flex items-center gap-2"><input type="radio" name="payment-plan-mode" checked={plan.mode === mode} onChange={() => update({ mode })} />{mode === 'PERCENTAGE' ? 'Percentage based' : mode === 'FIXED' ? 'Fixed amount' : 'Mixed'}</label>)}</div>
    <section className="space-y-3"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold uppercase tracking-wide text-dark-blue">Payment schedule</h3><button type="button" onClick={add} className="rounded-lg border border-dark-blue px-3 py-2 text-xs font-semibold text-dark-blue">+ Add payment stage</button></div>
      {plan.stages.map((stage, index) => <div key={stage.id} className="rounded-xl border border-gray-200 bg-white p-4 space-y-3"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-gray-500">Stage {index + 1}</span><button type="button" onClick={() => remove(index)} className="text-xs font-semibold text-red-700">Remove</button></div><div className="grid gap-3 md:grid-cols-4">{dropdown(stage.type, typeOptions, (value) => updateStage(index, { type: value as PaymentStage['type'] }), 'Type')}<label className="text-xs font-semibold text-gray-600">Label<input className={inputClass} value={stage.label} onChange={(e) => updateStage(index, { label: e.target.value })} /></label>{dropdown(stage.basis, [['PERCENTAGE', 'Percentage'], ['FIXED_AMOUNT', 'Fixed amount']], (value) => updateStage(index, { basis: value as PaymentStage['basis'] }), 'Basis')}<label className="text-xs font-semibold text-gray-600">{stage.basis === 'PERCENTAGE' ? 'Percentage' : 'Amount'}<input type="number" min="0" step="0.01" className={inputClass} value={(stage.basis === 'PERCENTAGE' ? stage.percentage : stage.fixedAmount) || ''} onChange={(e) => updateStage(index, stage.basis === 'PERCENTAGE' ? { percentage: Number(e.target.value) || 0 } : { fixedAmount: Number(e.target.value) || 0 })} /></label></div><div className="grid gap-3 md:grid-cols-3">{dropdown(stage.timingType, timingOptions, (value) => updateStage(index, { timingType: value as PaymentStage['timingType'] }), 'When')}<label className="text-xs font-semibold text-gray-600">Milestone / timing<input className={inputClass} value={stage.milestone || ''} onChange={(e) => updateStage(index, { milestone: e.target.value, timingValue: e.target.value })} placeholder="Foundation complete" /></label><label className="text-xs font-semibold text-gray-600">Installments<input type="number" min="1" className={inputClass} value={stage.installmentCount || ''} onChange={(e) => updateStage(index, { installmentCount: Number(e.target.value) || null })} /></label></div><p className="text-sm font-semibold text-dark-blue">Stage total: {money(calculation.stageResults[index]?.totalAmount || 0)}{calculation.stageResults[index]?.installmentAmount ? ` · ${money(calculation.stageResults[index].installmentAmount)} each` : ''}</p></div>)}
      {calculation.warnings.map((warning) => <p key={warning} role="alert" className="text-sm text-red-700">{warning}</p>)}<div className="flex flex-wrap gap-5 border-t border-gray-200 pt-3 text-sm font-semibold"><span>Scheduled: {money(calculation.scheduledPropertyPayments)}</span><span className={calculation.status === 'COMPLETE' ? 'text-emerald-700' : 'text-amber-700'}>{calculation.allocatedPercentage}% allocated</span><span>Remaining: {money(Math.max(0, calculation.remainingAmount))}</span></div></section>
    <section className="space-y-3"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold uppercase tracking-wide text-dark-blue">Additional one-time costs</h3><button type="button" onClick={addCost} className="rounded-lg border border-dark-blue px-3 py-2 text-xs font-semibold text-dark-blue">+ Add cost</button></div>{plan.additionalCosts.map((cost, index) => <div key={cost.id} className="grid gap-3 rounded-xl border border-gray-200 bg-white p-4 md:grid-cols-5"><label className="text-xs font-semibold text-gray-600">Category<input className={inputClass} value={cost.category} onChange={(e) => updateCost(index, { category: e.target.value })} /></label><label className="text-xs font-semibold text-gray-600">Label<input className={inputClass} value={cost.label} onChange={(e) => updateCost(index, { label: e.target.value })} placeholder="Registration fee" /></label>{dropdown(cost.basis, [['FIXED_AMOUNT', 'Fixed amount'], ['PERCENTAGE_OF_PROPERTY_PRICE', '% of property price'], ['PERCENTAGE_OF_LOAN', '% of loan']], (value) => updateCost(index, { basis: value as AdditionalCost['basis'] }), 'Basis')}<label className="text-xs font-semibold text-gray-600">{cost.basis === 'FIXED_AMOUNT' ? 'Amount' : 'Percentage'}<input type="number" min="0" className={inputClass} value={(cost.basis === 'FIXED_AMOUNT' ? cost.amount : cost.percentage) || ''} onChange={(e) => updateCost(index, cost.basis === 'FIXED_AMOUNT' ? { amount: Number(e.target.value) || 0 } : { percentage: Number(e.target.value) || 0 })} /></label><button type="button" onClick={() => update({ additionalCosts: plan.additionalCosts.filter((_, current) => current !== index) })} className="self-end pb-2 text-left text-xs font-semibold text-red-700">Remove</button></div>)}</section>
    <section className="space-y-3"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold uppercase tracking-wide text-dark-blue">Recurring ownership costs</h3><button type="button" onClick={addRecurring} className="rounded-lg border border-dark-blue px-3 py-2 text-xs font-semibold text-dark-blue">+ Add recurring cost</button></div>{plan.recurringCosts.map((cost, index) => <div key={cost.id} className="grid gap-3 rounded-xl border border-gray-200 bg-white p-4 md:grid-cols-5"><label className="text-xs font-semibold text-gray-600">Category<input className={inputClass} value={cost.category} onChange={(e) => updateRecurring(index, { category: e.target.value })} /></label><label className="text-xs font-semibold text-gray-600">Label<input className={inputClass} value={cost.label} onChange={(e) => updateRecurring(index, { label: e.target.value })} placeholder="Service charge" /></label>{dropdown(cost.basis, [['FIXED_AMOUNT', 'Fixed amount'], ['PER_SQ_FT', 'Per sq ft']], (value) => updateRecurring(index, { basis: value as RecurringCost['basis'] }), 'Basis')}<label className="text-xs font-semibold text-gray-600">{cost.basis === 'PER_SQ_FT' ? 'Rate / sq ft' : 'Amount'}<input type="number" min="0" className={inputClass} value={(cost.basis === 'PER_SQ_FT' ? cost.ratePerSquareFoot : cost.amount) || ''} onChange={(e) => updateRecurring(index, cost.basis === 'PER_SQ_FT' ? { ratePerSquareFoot: Number(e.target.value) || 0 } : { amount: Number(e.target.value) || 0 })} /></label><div className="flex items-end gap-2">{dropdown(cost.frequency || 'ANNUALLY', [['MONTHLY', 'Monthly'], ['QUARTERLY', 'Quarterly'], ['ANNUALLY', 'Annual']], (value) => updateRecurring(index, { frequency: value as RecurringCost['frequency'] }), 'Frequency')}<button type="button" onClick={() => update({ recurringCosts: plan.recurringCosts.filter((_, current) => current !== index) })} className="pb-2 text-xs font-semibold text-red-700">Remove</button></div><p className="text-xs text-gray-600 md:col-span-5">{String(cost.status || 'ESTIMATED').toLowerCase()} estimate: {money(calculation.recurringCostDetails[index]?.calculatedAmount || 0)} / {String(cost.frequency || 'ANNUALLY').toLowerCase()}</p></div>)}</section>
    <section className="space-y-3"><h3 className="text-sm font-semibold uppercase tracking-wide text-dark-blue">Financing / EMI</h3><div className="grid gap-3 md:grid-cols-4">{dropdown(financing.available, [['YES', 'Yes'], ['NO', 'No'], ['NOT_SPECIFIED', 'Not specified']], (value) => updateFinancing({ available: value as Financing['available'] }), 'Financing')}{dropdown(financing.source, [['BANK_MORTGAGE', 'Bank mortgage'], ['DEVELOPER_FINANCING', 'Developer financing'], ['ISLAMIC_FINANCING', 'Islamic financing'], ['CASH', 'Cash'], ['MIXED', 'Mixed'], ['NOT_SPECIFIED', 'Not specified']], (value) => updateFinancing({ source: value as Financing['source'] }), 'Source')}<label className="text-xs font-semibold text-gray-600">Loan-to-value %<input type="number" min="0" max="100" className={inputClass} value={financing.loanToValue || ''} onChange={(e) => updateFinancing({ loanToValue: Number(e.target.value) || null })} /></label><label className="text-xs font-semibold text-gray-600">Loan amount<input type="number" min="0" className={inputClass} value={financing.loanAmount || ''} onChange={(e) => updateFinancing({ loanAmount: Number(e.target.value) || null })} /></label><label className="text-xs font-semibold text-gray-600">Down payment<input type="number" min="0" className={inputClass} value={financing.downPayment || ''} onChange={(e) => updateFinancing({ downPayment: Number(e.target.value) || null })} /></label><label className="text-xs font-semibold text-gray-600">Interest rate %<input type="number" min="0" step="0.01" className={inputClass} value={financing.interestRate || ''} onChange={(e) => updateFinancing({ interestRate: Number(e.target.value) || null })} /></label><label className="text-xs font-semibold text-gray-600">Term (years)<input type="number" min="1" className={inputClass} value={financing.termYears || ''} onChange={(e) => updateFinancing({ termYears: Number(e.target.value) || null })} /></label>{dropdown(financing.interestType || 'NOT_SPECIFIED', [['FIXED', 'Fixed'], ['VARIABLE', 'Variable'], ['NOT_SPECIFIED', 'Not specified']], (value) => updateFinancing({ interestType: value as Financing['interestType'] }), 'Interest type')}</div><p className="text-xs text-gray-600">Estimated EMI: {calculation.estimatedEmi ? `${money(calculation.estimatedEmi)} / month` : 'Enter loan, rate, and term.'} Financing is separate from developer payments.</p></section>
    <section className="rounded-xl border border-dark-blue/10 bg-white p-4"><h3 className="text-sm font-semibold uppercase tracking-wide text-dark-blue">Financial summary</h3><div className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><p>Property price <strong className="float-right">{money(calculation.propertyPrice)}</strong></p><p>Property payments <strong className="float-right">{money(calculation.scheduledPropertyPayments)}</strong></p><p>One-time costs <strong className="float-right">{money(calculation.oneTimeCosts)}</strong></p><p>Recurring costs <strong className="float-right">{money(calculation.recurringCosts)}</strong></p><p>Financing <strong className="float-right">{calculation.estimatedEmi ? `${money(calculation.estimatedEmi)} / month` : 'Not configured'}</strong></p><p className="font-semibold">Plan status <strong className="float-right">{calculation.status}</strong></p></div></section>
  </div>
}