import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms and Conditions | MillionFlats Pvt Ltd.',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white py-12">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <article className="max-w-4xl">
          <h1 className="text-3xl md:text-4xl font-serif font-bold text-dark-blue">TERMS AND CONDITIONS</h1>
          <p className="mt-2 text-gray-700">MillionFlats Pvt. Ltd.</p>
          <p className="mt-1 text-gray-700">
            Last Updated: <span className="font-medium">11th Feb, 2026</span>
          </p>
          <p className="mt-1 text-gray-700">Jurisdiction: India (Primary) | UAE Operations Covered</p>

          <h2 className="mt-10 text-2xl font-serif font-bold text-dark-blue">1. INTRODUCTION AND ACCEPTANCE</h2>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">1.1 Overview</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            These Terms and Conditions (“Terms,” “Agreement”) constitute a legally binding agreement between you (“User,”
            “you,” “your”) and MillionFlats Pvt. Ltd. (“Company,” “we,” “us,” “our”) governing your access to and use of the
            MillionFlats platform, including our website www.millionflats.com, mobile applications, APIs, and all related
            services (collectively, the “Platform”) .
          </p>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">1.2 Electronic Record</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            This document is an Electronic Record in terms of the Information Technology Act, 2000 and the rules thereunder.
            This electronic record is generated by a computer system and does not require any physical or digital signatures .
          </p>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">1.3 Acceptance</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            By accessing, browsing, registering on, or using any part of our Platform, you acknowledge that you have read,
            understood, and expressly agree to be bound by these Terms and our Privacy Policy. If you do not agree with any
            provision hereof, you must immediately discontinue use of our Platform .
          </p>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">1.4 Amendments</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            We reserve the right to modify, amend, or update these Terms at any time at our sole discretion. The updated Terms
            will be posted on this page with a revised “Last Updated” date. Material changes will be notified at least 30 days
            in advance via email or prominent Platform notice. Your continued use of the Platform after such changes
            constitutes your acceptance of the revised Terms .
          </p>

          <h2 className="mt-10 text-2xl font-serif font-bold text-dark-blue">2. DEFINITIONS AND INTERPRETATION</h2>
          <div className="mt-4 overflow-x-auto">
            <table className="w-full border border-gray-200 text-sm">
              <thead className="bg-gray-50">
                <tr>
                  <th className="text-left p-3 border-b border-gray-200">Term</th>
                  <th className="text-left p-3 border-b border-gray-200">Definition</th>
                </tr>
              </thead>
              <tbody className="text-gray-700">
                <tr>
                  <td className="p-3 border-b border-gray-200">“Platform”</td>
                  <td className="p-3 border-b border-gray-200">
                    The website www.millionflats.com, mobile applications, APIs, and all associated digital services operated by
                    MillionFlats Pvt. Ltd.
                  </td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">“Services”</td>
                  <td className="p-3 border-b border-gray-200">
                    All offerings provided through the Platform, including but not limited to AI-powered property matching,
                    immersive 3D tours, Verix Trust Score<sup>™</sup> suite, VerixPro<sup>™</sup> agent scoring, ecosystem partner
                    referrals, and SaaS subscriptions
                  </td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">“User” / “You”</td>
                  <td className="p-3 border-b border-gray-200">
                    Any person who accesses or uses the Platform, including property buyers, sellers, investors, real estate
                    agents, developers, ecosystem partners, and visitors
                  </td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">“Agent”</td>
                  <td className="p-3 border-b border-gray-200">
                    Licensed real estate professionals registered on our Platform to list properties and connect with buyers
                  </td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">“Developer”</td>
                  <td className="p-3 border-b border-gray-200">
                    Property developers, builders, or their authorized representatives listing projects on our Platform
                  </td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">“Ecosystem Partner”</td>
                  <td className="p-3 border-b border-gray-200">
                    Third-party service providers (loans, legal, insurance, interior design, packers and movers, property
                    management, Vastu/Feng Shui) registered on our Platform
                  </td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">“Verix AI<sup>™</sup>”</td>
                  <td className="p-3 border-b border-gray-200">
                    Our proprietary artificial intelligence system that generates trust scores, property valuations, and
                    investment insights
                  </td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">“VerixPro<sup>™</sup>”</td>
                  <td className="p-3 border-b border-gray-200">Our agent verification and performance scoring system</td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">“Content”</td>
                  <td className="p-3 border-b border-gray-200">
                    All text, graphics, images, photographs, videos, 3D tours, software, data, and other materials available on the
                    Platform
                  </td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">“Subscription”</td>
                  <td className="p-3 border-b border-gray-200">
                    Paid access to certain premium features of the Platform on a recurring fee basis
                  </td>
                </tr>
                <tr>
                  <td className="p-3">Interpretation</td>
                  <td className="p-3">
                    Headings are for convenience only and shall not affect interpretation. Words importing the singular shall
                    include the plural and vice versa. References to “includes” shall be construed as “without limitation” .
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          <h2 className="mt-10 text-2xl font-serif font-bold text-dark-blue">3. OUR SERVICES AND ROLE CLARIFICATION</h2>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">3.1 What We Offer</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">MillionFlats is a technology platform providing the following Services:</p>
          <div className="mt-4 overflow-x-auto">
            <table className="w-full border border-gray-200 text-sm">
              <thead className="bg-gray-50">
                <tr>
                  <th className="text-left p-3 border-b border-gray-200">Service Category</th>
                  <th className="text-left p-3 border-b border-gray-200">Description</th>
                </tr>
              </thead>
              <tbody className="text-gray-700">
                <tr>
                  <td className="p-3 border-b border-gray-200">AI-Powered Property Discovery</td>
                  <td className="p-3 border-b border-gray-200">
                    Intelligent property matching based on user preferences and behavior
                  </td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">Immersive 3D Tours</td>
                  <td className="p-3 border-b border-gray-200">Interactive, walkable 3D virtual tours of properties</td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">Verix Trust Score<sup>™</sup></td>
                  <td className="p-3 border-b border-gray-200">
                    AI-generated scores for property authenticity, price fairness, investment potential, and legal compliance
                  </td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">VerixPro<sup>™</sup></td>
                  <td className="p-3 border-b border-gray-200">Agent verification, performance scoring, and badge system</td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">Listing Management</td>
                  <td className="p-3 border-b border-gray-200">
                    Tools for agents and developers to showcase properties with enhanced media
                  </td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">Ecosystem Partner Marketplace</td>
                  <td className="p-3 border-b border-gray-200">
                    Connection service between users and verified third-party service providers
                  </td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">SaaS Subscriptions</td>
                  <td className="p-3 border-b border-gray-200">
                    Premium tools and analytics for real estate professionals
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">3.2 What We Are NOT</h3>
          <p className="mt-3 text-gray-700 leading-relaxed font-semibold">
            CRITICAL DISCLAIMER: MILLIONFLATS IS NOT A REAL ESTATE BROKER, AGENT, OR INTERMEDIARY .
          </p>
          <p className="mt-3 text-gray-700 leading-relaxed">We Do NOT:</p>
          <div className="mt-4 overflow-x-auto">
            <table className="w-full border border-gray-200 text-sm">
              <thead className="bg-gray-50">
                <tr>
                  <th className="text-left p-3 border-b border-gray-200">Clarification</th>
                  <th className="text-left p-3 border-b border-gray-200">Details</th>
                </tr>
              </thead>
              <tbody className="text-gray-700">
                <tr>
                  <td className="p-3 border-b border-gray-200">❌ Charge commission on property transactions</td>
                  <td className="p-3 border-b border-gray-200">
                    Our revenue is from SaaS subscriptions and service fees, NOT deal-based commissions
                  </td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">❌ Act as a party to any sale/purchase/rental agreement</td>
                  <td className="p-3 border-b border-gray-200">
                    All transactions occur directly between buyers, sellers, agents, and developers
                  </td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">❌ Provide real estate brokerage services</td>
                  <td className="p-3 border-b border-gray-200">
                    We are a technology platform, not a licensed brokerage
                  </td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">❌ Negotiate prices or terms</td>
                  <td className="p-3 border-b border-gray-200">
                    Negotiations are strictly between the involved parties
                  </td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">❌ Handle payments for property transactions</td>
                  <td className="p-3 border-b border-gray-200">
                    We do not collect, hold, or process any property purchase payments
                  </td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">❌ Guarantee property listings or developer credentials</td>
                  <td className="p-3 border-b border-gray-200">
                    We provide tools and scores but users must perform their own due diligence
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">3.3 Our Role as an Intermediary</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            We operate as an intermediary under the Information Technology Act, 2000, and a lead generation platform under
            applicable real estate laws. Our role is limited to:
          </p>
          <div className="mt-3 text-gray-700 leading-relaxed space-y-1">
            <p>Providing technology tools for property discovery and marketing</p>
            <p>Generating and transmitting leads between interested parties</p>
            <p>Displaying information provided by agents, developers, and partners</p>
            <p>Facilitating connections between users and ecosystem partners</p>
          </div>

          <h2 className="mt-10 text-2xl font-serif font-bold text-dark-blue">4. ELIGIBILITY AND ACCOUNT REGISTRATION</h2>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">4.1 Eligibility Criteria</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            You may use our Platform only if you:
          </p>
          <div className="mt-3 text-gray-700 leading-relaxed space-y-1">
            <p>Are at least 18 years of age and legally competent to enter into binding contracts under the Indian Contract Act, 1872</p>
            <p>Have not been previously suspended or removed from our Platform</p>
            <p>Are not located in a jurisdiction where your use would violate applicable laws</p>
            <p>If you are accessing on behalf of a legal entity, you represent that you have the authority to bind such entity .</p>
          </div>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">4.2 Account Registration</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            To access certain features, you must create an account by providing accurate, current, and complete information.
            You agree to:
          </p>
          <div className="mt-3 text-gray-700 leading-relaxed space-y-1">
            <p>Maintain the confidentiality of your login credentials</p>
            <p>Promptly update your account information upon any changes</p>
            <p>Notify us immediately of any unauthorized use of your account</p>
            <p>Be fully responsible for all activities occurring under your account</p>
          </div>
          <p className="mt-3 text-gray-700 leading-relaxed">
            Verification: We may require verification of your identity, professional credentials (license numbers, RERA registrations),
            or business registration before granting access to certain features .
          </p>

          <h2 className="mt-10 text-2xl font-serif font-bold text-dark-blue">5. SUBSCRIPTION MODEL AND FEES</h2>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">5.1 SaaS Subscription Model</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            MillionFlats operates on a subscription-based technology platform model. We do not charge commissions, brokerage
            fees, or transaction-based fees .
          </p>
          <div className="mt-4 overflow-x-auto">
            <table className="w-full border border-gray-200 text-sm">
              <thead className="bg-gray-50">
                <tr>
                  <th className="text-left p-3 border-b border-gray-200">Plan Type</th>
                  <th className="text-left p-3 border-b border-gray-200">Features</th>
                  <th className="text-left p-3 border-b border-gray-200">Billing Cycle</th>
                </tr>
              </thead>
              <tbody className="text-gray-700">
                <tr>
                  <td className="p-3 border-b border-gray-200">Basic (Free)</td>
                  <td className="p-3 border-b border-gray-200">Limited property searches, basic listings, standard support</td>
                  <td className="p-3 border-b border-gray-200">N/A</td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">Professional</td>
                  <td className="p-3 border-b border-gray-200">Enhanced AI tools, 3D tour credits, lead management, analytics</td>
                  <td className="p-3 border-b border-gray-200">Monthly/Annual</td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">Enterprise</td>
                  <td className="p-3 border-b border-gray-200">Custom solutions, API access, white-label options, dedicated account manager</td>
                  <td className="p-3 border-b border-gray-200">Custom</td>
                </tr>
              </tbody>
            </table>
          </div>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">5.2 Payment Terms</h3>
          <div className="mt-3 text-gray-700 leading-relaxed space-y-1">
            <p>All fees are payable in advance unless otherwise agreed in writing .</p>
            <p>Payments are processed through our authorized payment gateways.</p>
            <p>Fees are non-refundable except as expressly stated in our Refund Policy or required by applicable law .</p>
            <p>Subscription fees are subject to applicable taxes, which are the User&apos;s responsibility.</p>
            <p>We reserve the right to modify our fee structure with appropriate notice .</p>
          </div>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">5.3 Fee Changes</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            We may revise subscription fees prospectively. For existing subscribers, fee changes will take effect at the next
            renewal period, provided we have given you at least 30 days&apos; prior notice .
          </p>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">5.4 Non-Payment</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            If your payment method fails or your account becomes delinquent, we reserve the right to suspend or terminate
            your access to paid Services.
          </p>

          <h2 className="mt-10 text-2xl font-serif font-bold text-dark-blue">6. USER OBLIGATIONS AND CONDUCT</h2>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">6.1 Accurate Information</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            You agree to provide true, accurate, current, and complete information on the Platform. You are solely responsible
            for the accuracy and completeness of all information you submit, including property listings, profile details, and
            inquiries .
          </p>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">6.2 Compliance with Laws</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            You agree to use the Platform in compliance with all applicable laws, including but not limited to:
          </p>
          <div className="mt-3 text-gray-700 leading-relaxed space-y-1">
            <p>RERA (Real Estate Regulation and Development) Act, 2016 – Developers and agents must provide valid RERA registration numbers and comply with all disclosure requirements .</p>
            <p>Information Technology Act, 2000 – Regarding data protection and cybersecurity.</p>
            <p>Consumer Protection Act, 2019 – Advertising and marketing practices.</p>
            <p>UAE Real Estate Laws – For properties and transactions in the UAE.</p>
          </div>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">6.3 Prohibited Activities</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">You are strictly prohibited from:</p>
          <div className="mt-3 text-gray-700 leading-relaxed space-y-2">
            <p className="font-medium">A. Content Violations:</p>
            <div className="space-y-1">
              <p>Posting false, misleading, deceptive, or fraudulent information</p>
              <p>Uploading content that infringes any third-party intellectual property rights</p>
              <p>Sharing defamatory, obscene, pornographic, abusive, threatening, or harassing content</p>
              <p>Posting content that violates any applicable law or regulation</p>
            </div>
            <p className="font-medium mt-2">B. Platform Abuse:</p>
            <div className="space-y-1">
              <p>Using bots, scrapers, crawlers, or other automated tools without our express written permission</p>
              <p>Reverse engineering, decompiling, or disassembling any portion of the Platform</p>
              <p>Interfering with or disrupting the security or functionality of the Platform</p>
              <p>Attempting to gain unauthorized access to any systems or networks</p>
              <p>Creating multiple accounts to circumvent restrictions</p>
            </div>
            <p className="font-medium mt-2">C. Commercial Misuse:</p>
            <div className="space-y-1">
              <p>Reselling, sublicensing, or commercially exploiting the Platform or its content without authorization</p>
              <p>Using the Platform for any illegal or unauthorized purpose</p>
              <p>Sending unsolicited messages, spam, or advertising to other users</p>
            </div>
            <p className="font-medium mt-2">D. RERA-Specific Violations:</p>
            <div className="space-y-1">
              <p>Developers and agents failing to provide valid RERA registration details where required</p>
              <p>Listing properties without necessary approvals and authorizations</p>
            </div>
          </div>
          <p className="mt-3 text-gray-700 leading-relaxed">
            Consequences: Violation of these prohibited activities may result in immediate suspension or termination of your
            account, forfeiture of subscription fees, and legal action as appropriate .
          </p>

          <h2 className="mt-10 text-2xl font-serif font-bold text-dark-blue">7. INTELLECTUAL PROPERTY RIGHTS</h2>
          <p className="mt-3 text-gray-700 leading-relaxed">
            All Intellectual Property Rights in and to the Platform, including but not limited to the Verix AI<sup>™</sup>,
            Verix Trust Score<sup>™</sup>, VerixPro<sup>™</sup>, and associated algorithms, the MillionFlats brand, logo,
            trademarks, and trade names, software, code, databases, and underlying technology, and 3D tour technology and
            immersive viewing tools are owned by MillionFlats Pvt. Ltd. or our licensors and are protected by Indian and
            international intellectual property laws .
          </p>
          <p className="mt-3 text-gray-700 leading-relaxed">
            Limited License: We grant you a personal, non-exclusive, non-transferable, revocable, limited license to access
            and use the Platform for its intended purposes.
          </p>

          <h2 className="mt-10 text-2xl font-serif font-bold text-dark-blue">8. VERIX AI<sup>™</sup> AND VERIXPRO<sup>™</sup> DISCLAIMERS</h2>
          <h3 className="mt-6 text-xl font-semibold text-dark-blue">8.1 AI-Generated Insights</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            Verix Trust Score<sup>™</sup>, VerixIndex<sup>™</sup>, VerixShield<sup>™</sup>, and VerixTitle<sup>™</sup> are
            AI-generated estimates and assessments based on available data, algorithms, and machine learning models. They are:
          </p>
          <div className="mt-3 text-gray-700 leading-relaxed space-y-1">
            <p>Not financial or legal advice</p>
            <p>Not guarantees of property value, investment performance, or legal status</p>
            <p>Estimates only and should not be solely relied upon for decision-making</p>
          </div>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">8.2 VerixPro<sup>™</sup> Agent Scores</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            VerixPro<sup>™</sup> scores are calculated based on platform activity, transaction history, user reviews, and
            verification data. These scores:
          </p>
          <div className="mt-3 text-gray-700 leading-relaxed space-y-1">
            <p>Represent past performance and platform engagement</p>
            <p>Are not endorsements or guarantees of future performance</p>
            <p>Should be verified through independent due diligence</p>
          </div>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">8.3 No Warranty of Accuracy</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            While we strive to improve our AI models, we do not warrant or guarantee the accuracy, completeness, reliability,
            or timeliness of any Verix AI<sup>™</sup> outputs. Users are solely responsible for conducting their own
            independent due diligence .
          </p>

          <h2 className="mt-10 text-2xl font-serif font-bold text-dark-blue">9. ECOSYSTEM PARTNERS AND THIRD-PARTY SERVICES</h2>
          <h3 className="mt-6 text-xl font-semibold text-dark-blue">9.1 Partner Relationships</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            MillionFlats partners with various third-party service providers (“Ecosystem Partners”) including home loan
            providers, legal firms, insurance companies, interior designers, packers and movers, property managers, and
            Vastu/Feng Shui consultants.
          </p>
          <p className="mt-3 text-gray-700 leading-relaxed">Our Role: We act as a referral and lead generation platform. We do not:</p>
          <div className="mt-3 text-gray-700 leading-relaxed space-y-1">
            <p>Employ, endorse, or guarantee the services of any Ecosystem Partner</p>
            <p>Assume any liability for services provided by Partners</p>
            <p>Participate in any agreements, payments, or disputes between Users and Partners</p>
          </div>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">9.2 User-Partner Transactions</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            All transactions, agreements, payments, and communications between Users and Ecosystem Partners are strictly
            between the parties. MillionFlats is not a party to such transactions and disclaims all liability arising
            therefrom.
          </p>
          <p className="mt-3 text-gray-700 leading-relaxed">
            Due Diligence: Users are strongly advised to independently verify the credentials, reputation, and service quality
            of any Ecosystem Partner before engaging their services.
          </p>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">9.3 Partner Listings</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            Partner profiles, ratings, and descriptions are provided by the Partners themselves. While we conduct basic
            verification, we do not independently verify all claims and disclaim all warranties regarding Partner
            information.
          </p>

          <h2 className="mt-10 text-2xl font-serif font-bold text-dark-blue">10. THIRD-PARTY LINKS AND ADVERTISEMENTS</h2>
          <p className="mt-3 text-gray-700 leading-relaxed">
            The Platform may contain links to third-party websites, advertisements, or services. These links are provided solely
            for your convenience and do not constitute our endorsement, approval, or responsibility for such third-party content .
          </p>
          <p className="mt-3 text-gray-700 leading-relaxed">We are not responsible for:</p>
          <div className="mt-3 text-gray-700 leading-relaxed space-y-1">
            <p>The content, accuracy, or availability of third-party sites</p>
            <p>The privacy practices, terms, or policies of third-party sites</p>
            <p>Any damage or loss arising from your use of or reliance on third-party content</p>
          </div>
          <p className="mt-3 text-gray-700 leading-relaxed">
            You access third-party links at your own risk and should review their applicable terms and policies.
          </p>

          <h2 className="mt-10 text-2xl font-serif font-bold text-dark-blue">11. DISCLAIMERS AND LIMITATION OF LIABILITY</h2>
          <h3 className="mt-6 text-xl font-semibold text-dark-blue">11.1 Disclaimer of Warranties</h3>
          <p className="mt-3 text-gray-700 leading-relaxed font-semibold">
            THE PLATFORM AND ALL SERVICES, CONTENT, AND FEATURES ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS, WITHOUT
            ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED .
          </p>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">11.2 Limitation of Liability</h3>
          <p className="mt-3 text-gray-700 leading-relaxed font-semibold">
            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL MILLIONFLATS PVT. LTD., ITS AFFILIATES,
            OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR:
          </p>

          <div className="mt-3 text-gray-700 leading-relaxed space-y-1">
            <p>ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES</p>
            <p>ANY LOSS OF PROFITS, REVENUES, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES</p>
            <p>ANY DAMAGES ARISING FROM YOUR ACCESS TO OR USE OF (OR INABILITY TO ACCESS OR USE) THE PLATFORM</p>
            <p>ANY CONDUCT OR CONTENT OF ANY THIRD PARTY, INCLUDING AGENTS, DEVELOPERS, OR ECOSYSTEM PARTNERS</p>
            <p>ANY UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT</p>
          </div>

          <p className="mt-3 text-gray-700 leading-relaxed">
            CAP ON LIABILITY: Our total cumulative liability to you for any and all claims arising out of or relating to
            these Terms or your use of the Platform shall not exceed the total subscription fees paid by you to us in the
            twelve (12) months immediately preceding the event giving rise to such liability .
          </p>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">11.3 Property and Transaction Disclaimer</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">MillionFlats does not guarantee:</p>
          <div className="mt-3 text-gray-700 leading-relaxed space-y-1">
            <p>The accuracy, completeness, or legality of any property listing or information</p>
            <p>The RERA registration status, approvals, or compliance of any project</p>
            <p>The financial stability, reputation, or bona fides of any developer, agent, or seller</p>
            <p>The timely completion, quality, or delivery of any under-construction project</p>
            <p>The successful outcome of any transaction initiated through the Platform</p>
          </div>
          <p className="mt-3 text-gray-700 leading-relaxed">
            Users are solely responsible for conducting their own independent due diligence before making any real estate
            decision or entering into any transaction .
          </p>

          <h2 className="mt-10 text-2xl font-serif font-bold text-dark-blue">12. INDEMNIFICATION</h2>
          <p className="mt-3 text-gray-700 leading-relaxed">
            You agree to indemnify, defend, and hold harmless MillionFlats Pvt. Ltd., its affiliates, officers, directors,
            employees, agents, and successors from and against any and all claims, demands, liabilities, damages, losses,
            costs, and expenses (including reasonable attorneys&apos; fees) arising out of or relating to:
          </p>
          <div className="mt-3 text-gray-700 leading-relaxed space-y-1">
            <p>Your access to or use of the Platform</p>
            <p>Any content you submit, post, or transmit through the Platform</p>
            <p>Your violation of these Terms or any applicable law</p>
            <p>Your violation of any rights of any third party, including intellectual property rights, privacy rights, or contractual rights</p>
            <p>Any dispute between you and any other User, Developer, Agent, or Ecosystem Partner</p>
          </div>
          <p className="mt-3 text-gray-700 leading-relaxed">
            We reserve the right to assume the exclusive defense and control of any matter subject to indemnification by you,
            in which case you agree to cooperate with us in asserting any available defenses.
          </p>

          <h2 className="mt-10 text-2xl font-serif font-bold text-dark-blue">13. TERM AND TERMINATION</h2>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">13.1 Term</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            These Terms shall remain in full force and effect as long as you continue to access or use the Platform, and
            indefinitely thereafter with respect to surviving provisions .
          </p>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">13.2 Termination by Us</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">We reserve the right, in our sole discretion, to:</p>
          <div className="mt-3 text-gray-700 leading-relaxed space-y-1">
            <p>Suspend or terminate your access to the Platform or any portion thereof</p>
            <p>Remove or disable access to any content you have submitted</p>
            <p>Block your account and prevent further registration</p>
          </div>
          <p className="mt-3 text-gray-700 leading-relaxed">
            ... at any time, without prior notice or liability, for any reason whatsoever, including but not limited to a
            breach of these Terms or applicable law .
          </p>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">13.3 Termination by You</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">You may terminate your account at any time by:</p>
          <div className="mt-3 text-gray-700 leading-relaxed space-y-1">
            <p>Using the account deletion feature available in your account settings, or</p>
            <p>Sending a written request to support@millionflats.com</p>
          </div>
          <p className="mt-3 text-gray-700 leading-relaxed">
            Upon termination, your right to access and use the Platform will immediately cease. Certain provisions of these
            Terms shall survive termination, including but not limited to Sections 7 (Intellectual Property), 11 (Limitation of
            Liability), 12 (Indemnification), and 15 (Governing Law and Dispute Resolution) .
          </p>

          <h2 className="mt-10 text-2xl font-serif font-bold text-dark-blue">14. COMMUNICATIONS AND CONSENT</h2>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">14.1 Consent to Contact</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            By providing your contact information (including phone number, email address, and any messaging app identifiers)
            through the Platform, you expressly consent to receive communications from:
          </p>
          <div className="mt-3 text-gray-700 leading-relaxed space-y-1">
            <p>MillionFlats regarding your account, inquiries, services, and promotional offers</p>
            <p>Agents, developers, or sellers regarding properties you have expressed interest in</p>
            <p>Ecosystem Partners regarding services you have requested</p>
          </div>
          <p className="mt-3 text-gray-700 leading-relaxed">
            Such communications may be via telephone calls, SMS, email, WhatsApp, or other electronic means, regardless of
            whether your number is registered on any Do Not Call (DNC) registry .
          </p>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">14.2 Opt-Out</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">You may opt out of receiving non-essential marketing communications at any time by:</p>
          <div className="mt-3 text-gray-700 leading-relaxed space-y-1">
            <p>Clicking the “unsubscribe” link in any promotional email</p>
            <p>Replying “STOP” to SMS communications</p>
            <p>Updating your communication preferences in account settings</p>
            <p>Contacting us directly</p>
          </div>
          <p className="mt-3 text-gray-700 leading-relaxed">
            Please note that even after opting out, you may continue to receive transactional and service-related communications
            (e.g., account updates, payment confirmations, security alerts).
          </p>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">14.3 Call Recording</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            We may record calls with you for quality assurance, training, and record-keeping purposes. By engaging in a call
            with our representatives, you consent to such recording .
          </p>

          <h2 className="mt-10 text-2xl font-serif font-bold text-dark-blue">15. GOVERNING LAW AND DISPUTE RESOLUTION</h2>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">15.1 Governing Law</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            These Terms shall be governed by and construed in accordance with the laws of India. Any disputes arising out of
            or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in [Insert City,
            State - e.g., Mumbai, Maharashtra] .
          </p>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">15.2 Dispute Resolution – Arbitration</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            Any dispute, controversy, or claim arising out of or relating to these Terms or the breach, termination, or
            validity thereof shall be finally resolved by arbitration in accordance with the Arbitration and Conciliation Act,
            1996.
          </p>
          <div className="mt-3 text-gray-700 leading-relaxed space-y-1">
            <p>Arbitration Venue: Rajkot, Gujarat, India</p>
            <p>Language: English</p>
            <p>Number of Arbitrators: One (1) mutually appointed sole arbitrator</p>
            <p>Binding Effect: The arbitration award shall be final and binding upon the Parties .</p>
          </div>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">15.3 Class Action Waiver</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            You agree that any proceedings to resolve or litigate any dispute will be conducted solely on an individual basis,
            and that you will not seek to have any dispute heard as a class action, representative action, consolidated
            action, or private attorney general action .
          </p>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">15.4 Injunctive Relief</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            Notwithstanding the foregoing, either Party may seek injunctive or other equitable relief from a court of
            competent jurisdiction to protect its intellectual property rights or confidential information.
          </p>

          <h2 className="mt-10 text-2xl font-serif font-bold text-dark-blue">16. UAE-SPECIFIC PROVISIONS</h2>
          <p className="mt-3 text-gray-700 leading-relaxed">
            For Users accessing our Platform from or transacting in properties located in the United Arab Emirates, the
            following additional provisions apply:
          </p>
          <div className="mt-3 text-gray-700 leading-relaxed space-y-1">
            <p>
              UAE Real Estate Law: Users acknowledge that all property transactions in the UAE are governed by the laws of the
              respective Emirate and federal UAE laws.
            </p>
            <p>
              Dubai Land Department (DLD): Properties listed in Dubai shall comply with DLD regulations, and agents/developers
              must provide valid broker license numbers.
            </p>
            <p>
              Cross-Border Data Transfer: Users consent to the transfer of their Personal Data between India and the UAE for the
              purpose of providing Services .
            </p>
            <p>
              Currency: All fees for UAE-related services shall be denominated in AED and converted to INR for billing purposes
              where applicable.
            </p>
          </div>
          <p className="mt-3 text-gray-700 leading-relaxed">
            In the event of any conflict between the main Terms and these UAE-specific provisions, the UAE-specific provisions
            shall prevail for Users and transactions within the UAE.
          </p>

          <h2 className="mt-10 text-2xl font-serif font-bold text-dark-blue">17. MISCELLANEOUS PROVISIONS</h2>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">17.1 Entire Agreement</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            These Terms, together with our Privacy Policy and any other policies expressly incorporated by reference,
            constitute the entire agreement between you and MillionFlats regarding your use of the Platform and supersede all
            prior agreements and understandings, whether written or oral .
          </p>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">17.2 Severability</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            If any provision of these Terms is held to be invalid, illegal, or unenforceable under applicable law, such
            provision shall be limited or eliminated to the minimum extent necessary, and the remaining provisions shall
            remain in full force and effect .
          </p>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">17.3 Waiver</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            No failure or delay by MillionFlats in exercising any right, power, or remedy under these Terms shall operate as a
            waiver thereof. Any waiver must be in writing and signed by an authorized representative of MillionFlats .
          </p>

          <h3 className="mt-6 text-xl font-semibold text-dark-blue">17.4 Assignment</h3>
          <p className="mt-3 text-gray-700 leading-relaxed">
            You may not assign or transfer these Terms, by operation of law or otherwise, without our prior written consent.
            We may assign or transfer these Terms, in whole or in part, without restriction .
          </p>

          <h2 className="mt-10 text-2xl font-serif font-bold text-dark-blue">18. CONTACT INFORMATION</h2>
          <p className="mt-3 text-gray-700 leading-relaxed">For any questions, concerns, or inquiries regarding these Terms, please contact us at:</p>
          <div className="mt-4 overflow-x-auto">
            <table className="w-full border border-gray-200 text-sm">
              <thead className="bg-gray-50">
                <tr>
                  <th className="text-left p-3 border-b border-gray-200">Purpose</th>
                  <th className="text-left p-3 border-b border-gray-200">Contact Details</th>
                </tr>
              </thead>
              <tbody className="text-gray-700">
                <tr>
                  <td className="p-3 border-b border-gray-200">General Inquiries</td>
                  <td className="p-3 border-b border-gray-200">info@millionflats.com</td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">Support</td>
                  <td className="p-3 border-b border-gray-200">support@millionflats.com</td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">Legal Notices</td>
                  <td className="p-3 border-b border-gray-200">info@millionflats.com</td>
                </tr>
                <tr>
                  <td className="p-3 border-b border-gray-200">Grievance Officer</td>
                  <td className="p-3 border-b border-gray-200">info@millionflats.com</td>
                </tr>
                <tr>
                  <td className="p-3">Registered Address</td>
                  <td className="p-3">Rajkot-360005, Gujarat, India</td>
                </tr>
              </tbody>
            </table>
          </div>

          <p className="mt-8 text-gray-700 leading-relaxed">
            Disclaimer: These documents are drafted based on extensive analysis of industry-standard templates and applicable
            Indian and UAE laws. However, they do not constitute legal advice. You are strongly advised to have these documents
            reviewed by a qualified legal professional in India (and separately in the UAE) to ensure full compliance with all
            applicable laws and regulations specific to your business operations and registered jurisdiction.
          </p>
        </article>
      </div>
    </div>
  )
}
