ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_ECOSYSTEM_BANNER_UPLOADED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_ECOSYSTEM_BANNER_REPLACED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_ECOSYSTEM_BANNER_REMOVED';
