-- Adds missing scalar columns on users used by auth and onboarding flows.

ALTER TABLE users
ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS email_verified_by_admin_id TEXT,
ADD COLUMN IF NOT EXISTS image TEXT,
ADD COLUMN IF NOT EXISTS password_hash TEXT,
ADD COLUMN IF NOT EXISTS google_id TEXT,
ADD COLUMN IF NOT EXISTS age_group TEXT,
ADD COLUMN IF NOT EXISTS purpose TEXT,
ADD COLUMN IF NOT EXISTS interested_country TEXT,
ADD COLUMN IF NOT EXISTS budget_min DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS budget_max DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS buying_timeline TEXT,
ADD COLUMN IF NOT EXISTS investment_goal TEXT,
ADD COLUMN IF NOT EXISTS marketing_consent BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS profile_completed_at TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS onboarding_version INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS current_onboarding_step INTEGER NOT NULL DEFAULT 1;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS preferred_language TEXT,
ADD COLUMN IF NOT EXISTS auth_provider TEXT,
ADD COLUMN IF NOT EXISTS last_device TEXT,
ADD COLUMN IF NOT EXISTS last_ip TEXT,
ADD COLUMN IF NOT EXISTS profile_completion INTEGER NOT NULL DEFAULT 0;
